#!/usr/bin/env bash

set -eo pipefail

apt-get update
apt-get install -y git
cd /app
rm -rf .git
rm -f .gitignore
git init .
git remote add origin https://github.com/camptocamp/puppetboard.git
git remote update
git checkout epfl_pdb3
